apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: color-app
          env:
            - name: APP_COLOR
              value: "green"
