apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jasperjumelet/kubernetesartifacts.git'
    targetRevision: HEAD
    # This tells ArgoCD to run Kustomize on this specific overlay directory
    path: services/colorapp/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: color-app # The actual K8s namespace where your app code will live
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically creates the 'staging' namespace if it doesn't exist